/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_pollux_modifydalvikbytecode_MainActivity */

#ifndef _Included_cn_pollux_modifydalvikbytecode_MainActivity
#define _Included_cn_pollux_modifydalvikbytecode_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_pollux_modifydalvikbytecode_MainActivity
 * Method:    modifyBytecode
 * Signature: ()I
 */

JNIEXPORT jint JNICALL Java_cn_pollux_modifydalvikbytecode_MainActivity_modifyBytecode
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif